name: PR Workflow

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Hello, this PR was just opened!"

      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: success # або 'failure' в залежності від вашої логіки
          fields: |
            Title: Pull Request Notification
            Description: A new pull request has been opened or reopened.
            Link: ${{ github.event.pull_request.html_url }} # Додаємо посилання на PR
          github_token: ${{ secrets.GITHUB_TOKEN }}
